spring:
  application:
    name: food
  main:
    banner-mode: "off"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
        show_sql: false
        highlight_sql: true
  mvc:
    log-request-details: true
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

external:
  api:
    url: "https://world.openfoodfacts.net/api/v2/product/"

logging:
  level:
    root: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.transaction: DEBUG
    com.x5.food: DEBUG

  file:
    name: logs/app.log

