
spring:
  application:
    name: food
  main:
    banner-mode: "off" #annoyng
  datasource:
    hikari:
      health-check:
        enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: warrior
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

#endpoints actuator and health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true



