### Test DB barcodes
# @name TestDBBarcodes
GET {{baseUrl}}/api/barcode/{{db_barcodes}{each}}
Accept: {{contentType}}

> {%
    client.test("Barcode should be found", function () {
        client.assert(response.status === 200, "Should find barcode in DB");
    });
%}

###
### Test non DB but ext API barcodes
# @name TestExtBarcodes



GET {{baseUrl}}/api/barcode/{{external_barcodes}{each}}
Accept: {{contentType}}

> {%
    client.test("Barcode should be found", function () {
        client.assert(response.status === 201, "Should find barcode in DB");
    });
%}

###
### Test missing barcode
# @name TestMissingBarcode
GET {{baseUrl}}/api/barcode/{{missing_barcodes[0]}}

> {%
    client.test("Missing barcode returns 404", function () {
        client.assert(response.status === 404, "Should return 404 for missing barcode");
    });
%}

###